WedSiteBanHang/WedSiteBanHang/Controllers/QuanLyPhieuNhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WedSiteBanHang.Models;

namespace WedSiteBanHang.Controllers
{
    [Authorize(Roles = "QuanTri,QuanLySanPham")]
    public class QuanLyPhieuNhapController : Controller
    {
        // GET: QuanLyPhieuNhap
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        [HttpGet]
        public ActionResult NhapHang()
        {
            ViewBag.MaNCC = db.NhaCungCaps;
            ViewBag.ListSanPham = db.SanPhams;

            return View();
        }
        [HttpPost]
        public ActionResult NhapHang(PhieuNhap model, IEnumerable<ChiTietPhieuNhap> lstModel)
        {
            ViewBag.MaNCC = db.NhaCungCaps;
            ViewBag.ListSanPham = db.SanPhams;
            //Sau khi các bạn đã kiểm tra tất cả dữ liệu đầu vào
            //Gán đã xóa: False
            model.DaXoa = false;
            db.PhieuNhaps.Add(model);
            db.SaveChanges();
            //SaveChanges để lấy được mã phiếu nhập gán cho lstChitietphieunhap
            SanPham sp;
            foreach (var item in lstModel)

            {
                //Cập nhật số lượng tồn
                sp = db.SanPhams.Single(n => n.MaSP == item.MaSP);
                sp.SoLuongTon += item.SoLuongNhap;
                sp.DonGia = item.DonGiaNhap;
                //gán mã phiếu nhập cho tất cả chi tiết phiếu nhập
                item.MaPN = model.MaPN;
            }
            db.ChiTietPhieuNhaps.AddRange(lstModel);
            db.SaveChanges();
            return View();
        }
        [HttpGet]
        public ActionResult DSSHetHang()
        {
            var lstSP = db.SanPhams.Where(n => n.DaXoa == false && n.SoLuongTon <= 35);


            return View(lstSP);
        }
        //Tạo 1 view phục vụ việc nhập từng sản phẩm
        [HttpGet]
        public ActionResult NhapHangDon(int? id)
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            //Tương tự như trang chỉnh sửa sản phẩm nhưng ta không cần phaari show hết các thuộc tính
            //Chỉ thuộc tính nào cần thiết mà thôi đó là số lượng tồn hình ảnh.. thông tin hiển thị cần thiết
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }
        //Xử lý nhập hàng từng sản phẩm
        [HttpPost]
        public ActionResult NhapHangDon(PhieuNhap model, ChiTietPhieuNhap ctpn)
            {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", model.MaNCC);
            //Sau khi các bạn đã kiểm tra tất cả dữ liệu đầu vào
            //Gán đã xóa: False
            model.NgayNhap = DateTime.Now;
            model.DaXoa = false;
            db.PhieuNhaps.Add(model);
            db.SaveChanges();
            //SaveChanges để lấy được mã phiếu nhập gán cho lstChitietphieunhap
            ctpn.MaPN = model.MaPN;
            //Cập nhật tồn
            SanPham sp = db.SanPhams.Single(n => n.MaSP == ctpn.MaSP);
            sp.SoLuongTon += ctpn.SoLuongNhap;
            db.ChiTietPhieuNhaps.Add(ctpn);
            db.SaveChanges();
            return View();
            }
        //Giải phóng biến cho vùng nhớ
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(db != null)
                {
                    db.Dispose();
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
        }
    }
}

WedSiteBanHang/WedSiteBanHang/Views/QuanLyPhieuNhap/DSSHetHang.cshtml
@using WedSiteBanHang.Models;
@model IEnumerable<SanPham>

@{

    ViewBag.Title = "DSSHetHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}
<h2>Danh sách các sản phẩm gần hết hàng</h2>
<br /><br />

@grid.GetHtml(
    tableStyle: "divTable", 
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
        grid.Column("MaSP", "Mã sản phẩm"),
        grid.Column("TenSP", "Tên sản phẩm"),

        grid.Column("HinhAnh", "Hình ảnh", format: p => @Html.Raw("<img width=\"150\" height=\"50\" src=\"../Content/images/" + p.HinhAnh + "\">")),
        grid.Column(format: p => Html.ActionLink("Nhập hàng", "NhapHangDon", new { id = p.MaSP }, new {@target="_blank" }))
  


        ))
<style>
       .divTable {
           width: 100%;
           border: 1px solid #999999;
       }

           .divTable td {
               border: 1px solid #999999;
           }

       .gridHead {
           background-color: green;
       }

           .gridHead > th > a {
               color: #fff;
           }

       .gridFooter {
           font-weight: bold;
       }
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>

WedSiteBanHang/WedSiteBanHang/Views/QuanLyPhieuNhap/NhapHang.cshtml
@using WedSiteBanHang.Models;
@model PhieuNhap

@{
    ViewBag.Title = "NhapHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
@{ 
    IEnumerable<NhaCungCap> lstNCC = ViewBag.MaNCC as IEnumerable<NhaCungCap>;
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
<script src="//code.jquery.com/jquery-3.6.0.js"></script>
<script src="//code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
<script>
  $( function() {
    $( ".date" ).datepicker();
  } );
</script>

@using (Html.BeginForm())
{ 
<div class="row">
    <div class="ThongTinPhieuNhap col-md-12">
        <div class="col-md-2">
            Nhà cung cấp
        </div>
        <div class="col-md-5">
         
            <select class="MaNCC" name="MaNCC" style="width:172px">
                @foreach (var item in lstNCC)
                {
                    <option value="@item.MaNCC">@item.TenNCC</option>
                    }
            </select>
        </div>
    </div>
</div>
<div class="col-md-12">

    <div class="col-md-2" style="top:20px">
        Ngày nhập
    </div>
    <div class="col-md-5" style="top:20px">
        <input class="date" name="NgayNhap" type="text"  />
    </div>
</div>
<div class="clearfix">  </div>
<br /><br /><br />

<table class="table tblChiTietPhieuNhap">
    @{IEnumerable<SanPham> lstSanPham = ViewBag.ListSanPham as IEnumerable<SanPham>; }
    <tr class="trAppend" style="display:none">
        <td>
            <select class="ddlSanPham" name=""  >
                @foreach (var item in lstSanPham)
                {
                    <option value="@item.MaSP"> @item.TenSP</option>
                }
            </select>
        </td>
        <td>
            <input name="" class="txtDonGia" value="0" />

        </td>
        <td>
            <input name="" class="txtSoLuong" value="0" />
           
        </td>
        <td>
            <input class="btnDelete btn btn-danger" style="width:30px; height:30px" value="-" />

        </td>
    </tr>
 
    <tr class="trFirstChild" data-id="-1">
        <td>Sản phẩm</td>
        <td>Đơn giá nhập</td>
        <td>Số lượng nhập</td>
        <td></td>
    </tr>
</table>

<input type="button" value="+" class="btn btn-success" id="btnAdd" />
<input type="submit" value="Nhập hàng" class="btn btn-primary" id="btnNhapHang" />
        }
<script>
    $("#btnAdd").click(function () {
      
   
        var id_cuoi = $(".tblChiTietPhieuNhap").find("tr:last-child").attr("data-id");
      i = parseInt(id_cuoi) + 1;
  
    var tdnoidung = $(".trAppend").html();
   
     var trnoidung = "<tr class=\"trAppended\" data-id=\"" + i + "\">" + tdnoidung + "</tr>";
    
    $(".tblChiTietPhieuNhap").append(trnoidung);
      loadIDLENTHE();
    });
  
    function loadIDLENTHE() {
        $(".trAppended").each(function () {
   
            var id = $(this).attr("data-id");
            var nameMaSanPham = "[" + id + "].MaSP";
            var nameSoLuongNhap = "[" + id + "].SoLuongNhap";
            var nameDonGiaNhap = "[" + id + "].DonGiaNhap";
            $(this).find(".ddlSanPham").prop("name", nameMaSanPham);
            $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);
            $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);
        });
    };

    function CapNhapID()
    {
        var id_cuoi = $(".tblChiTietPhieuNhap").find(".trFirstChild").attr("data-id");
        i = parseInt(id_cuoi) + 1;

        $(".trAppended").each(function () {
            var id = i;
            $(this).attr("data-id", i);
           
        var nameMaSanPham = "[" + id + "].MaSP";
        var nameSoLuongNhap = "[" + id + "].SoLuongNhap";
        var nameDonGiaNhap = "[" + id + "].DonGiaNhap";
        $(this).find(".ddlSanPham").prop("name", nameMaSanPham);
        $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);
        $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);
        i++;
        });
    }
   
    $("body").delegate(".btnDelete", "click", function () {
        $(this).closest(".trAppended").remove();
        CapNhapID();
    });
    $("#btnNhapHang").click(function(){
        if(kiemtraDonGia() == false)
        {
            
            return false;
        }
        if (kiemtraSoLuong() == false) {
          
            return false;
        }
       
    });
 
    function kiemtraDonGia() {
        var bl = true;
        
        $(".txtDonGia").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Đơn giá không hợp lệ!");
                bl = false;
                return bl;
            }
        });
        return bl;
    }
   
    function kiemtraSoLuong() {
        var bl = true;
        $(".txtSoLuong").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Số lượng không hợp lệ!");
                bl = false;
                return bl;
            }
        });
        return bl;
    }
    
</script>

WedSiteBanHang/WedSiteBanHang/Views/QuanLyPhieuNhap/NhapHangDon.cshtml
@using WedSiteBanHang.Models;
@model SanPham


@{
    ViewBag.Title = "NhapHangDon";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<legend>Nhập hàng cho sản phẩm <b>@Model.TenSP</b> </legend>
<hr />
<br />
<div class="row">
     <div class="col-md-3">
         <div class="imgSP">
             <img src="@Url.Content("~/Content/images/"+Model.HinhAnh)" />
         </div>
     </div>
    <div class="col-md-9" style="left:250px;">
        <div class="ttSP">
             <h3>Hãng sản xuất: @Model.NhaSanXuat.TenNSX</h3>
            <h3>Loại sản phẩm: @Model.LoaiSanPham.TenLoai</h3>
            <h3>Số lượng tồn: @Model.SoLuongTon</h3>
    </div>
        </div>
 </div>
<br />
<fieldset>
    <legend>Thông tin nhập hàng</legend>
</fieldset>
@using (Html.BeginForm("NhapHangDon", "QuanLyPhieuNhap"))
{
  @Html.Hidden("MaSP",Model.MaSP)
    <div class="row">
        <div class="col-md-4">
            @{ var lstNCC = (SelectList)ViewBag.MaNCC;}
            Nhà cung cấp: @Html.DropDownList("MaNCC", lstNCC, new { @class="MaNCC"})
        </div>
        <div class="col-md-4">
            Số lượng nhập: @Html.TextBox("SoLuongNhap")
        </div>
        <div class="col-md-4">
            Đơn giá nhập: @Html.TextBox("DonGiaNhap")
        </div>
        <div class="col-md-4">
           
        </div>
    </div>
    <div class="clear right" style="text-align:right;">
        <br />
        <input type="submit" class="btn btn-primary" value="Nhập hàng" style="margin-right: 50px;"/>
    </div>
}