WedSiteBanHang/WedSiteBanHang/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WedSiteBanHang.Models;

using PagedList;

namespace WedSiteBanHang.Controllers
{
    public class TimKiemController : Controller
    {
        // GET: TimKiem
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        [HttpGet]
        public ActionResult KQTimKiem(string sTuKhoa, int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int PageSize = 6;
            //Tạo biến thứ 2: Số trang hiện tại
            int PageNumber = (page ?? 1);
            //Tim kiems theo tên sản phẩm
            var lstSP = db.SanPhams.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return View(lstSP.OrderBy(n =>n.TenSP).ToPagedList(PageNumber, PageSize));
        }

        [HttpPost]
        public ActionResult LayTuKhoaTimKiem(string sTuKhoa)
        {
          //Gọi hàm get tìm kiếm
            return RedirectToAction("KQTimKiem", new { @sTuKhoa = sTuKhoa});
        }
        public ActionResult KQTimKiemPartial(string sTuKhoa)
        {
            //Tim kiems theo tên sản phẩm
            var lstSP = db.SanPhams.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return PartialView(lstSP.OrderBy(n=>n.DonGia));
        }
    }
}

WedSiteBanHang/WedSiteBanHang/Views/TimKiem/KQTimKiem.cshtml
@using WedSiteBanHang.Models
@using PagedList.Mvc;
@model PagedList.IPagedList<SanPham>

@{
    ViewBag.Title = "KQTimKiem";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}

<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@using (Ajax.BeginForm("KQTimKiemPartial", "TimKiem", new AjaxOptions { UpdateTargetId = "KQTimKiem", InsertionMode = InsertionMode.Replace }))
{
    <div class="search">
        <input style="width: 100px;" type="text" id="txtTimKiem" value="" name="sTuKhoa" placeholder="Nhập vào tên sản phẩm cần tìm kiếm" />
        <input type="submit" id="btnTimKiem" value="Tìm kiếm" />
    </div>
}


    <div id="KQTimKiem">
        <div class="col-md-9 product1">
            <div class="bottom-product">
                @foreach (var item in Model.OrderBy(n => n.DonGia))
                {
                    <div class="col-md-4 bottom-cd simpleCart_shelfItem">
                        <div class="product-at ">
                            <a href="single.html">
                                <img class="img-responsive" src="@Url.Content("~/Content/images/"+ item.HinhAnh)" alt="" style="width: 150px; height: 150px">
                                <div class="pro-grid">
                                    <span class="buy-in">Đặt Mua</span>
                                </div>
                            </a>
                        </div>
                        <p class="tun">@item.TenSP</p>
                    
                        <a href="@Url.Action("ThemGioHang","GioHang", new { @MaSP = item.MaSP, @strURL = Request.Url.ToString()})" class="item_add"><p class="number item_price"><i> </i>@item.DonGia.Value.ToString("#,##")</p></a>
                    </div>
                    }


                <div class="clearfix"> </div>

            </div>

        </div>
        <div class="dlink">
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("KQTimKiem", new { page = page, @sTuKhoa = ViewBag.TuKhoa }))
        </div>
    </div>
<style>
    #btnTimKiem{
        background-color: #4cae4c;
        color: #fff;
        padding: 0;
        font-size: 1.1em;
        font-weight: 600;
        margin-right: 0;
        border-radius: 0;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        -o-border-radius: 3px;
        outline: none;
        border: none;
        cursor: pointer;
        position: absolute;
        left: 204px;
        padding: 3px;

        
    }
    #txtTimKiem{
        width: 200px;
        border: 1px solid #000;
    }
</style>

WedSiteBanHang/WedSiteBanHang/Views/TimKiem/KQTimKiemPartial.cshtml
@model IEnumerable<WedSiteBanHang.Models.SanPham>
    @{ 
        
        int iDem = 0; 
        int iSLSanPhamTrenTrang = 6;
        int iTrang = 1;
    }
<div class="col-md-9 product1">
    <div class="bottom-product">
        @foreach (var item in Model.OrderBy(n => n.DonGia))
        {
            if(iDem % iSLSanPhamTrenTrang == 0 && iDem != 0)
            {
                iTrang++;
            }
            <div class="@Url.Content("col-md-4 bottom-cd simpleCart_shelfItem Trang" +iTrang.ToString())">
                <div class="product-at ">
                    <a href="single.html">
                        <img class="img-responsive" src="@Url.Content("~/Content/images/"+ item.HinhAnh)" alt="" style="width: 150px; height: 150px">
                        <div class="pro-grid">
                            <span class="buy-in">Đặt Mua</span>
                        </div>
                    </a>
                </div>
                <p class="tun">@item.TenSP</p>
              
                <a href="@Url.Action("ThemGioHang","GioHang", new { @MaSP = item.MaSP, @strURL = Request.Url.ToString()})" class="item_add"><p class="number item_price"><i> </i>@item.DonGia.Value.ToString("#,##")</p></a>
            </div>
            iDem++;
        }


        <div class="clearfix"> </div>

    </div>
    <div class="Trang">
        @for (int i = 1; i <= iTrang; i++)
        {
            <a class="@Url.Content("Trang"+i) linkTrang" data-sotrang href="#">@i</a>
        }
       
    </div>
</div>

<style>
    .simpleCart_shelfItem{
        display:none;
    }
    .Trang1{
        display:block;
    }
    .pagination {
    display: none;
    padding-left: 0;
    margin: 20px 0;
    border-radius: 4px;
     }
</style>

<script>
    $('.linkTrang').Click(function(){
        $(".simpleCart_shelfItem").hide();

        var soTrang = $(this).attr("data=sotrang");
     
        $("."+soTrang).show();
});
</script>