WedSiteBanHang/WedSiteBanHang/Controllers/DangKyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WedSiteBanHang.Controllers
{
    [Authorize(Roles = "DangKy")]
    public class DangKyController : Controller
    {
        // GET: DangKy
        public ActionResult Index()
        {
            return View();
        }
    }
}

WedSiteBanHang/WedSiteBanHang/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WedSiteBanHang.Models;
using CaptchaMvc.HtmlHelpers;
using CaptchaMvc;
using System.Web.Security;

namespace WedSiteBanHang.Controllers
{
    
    public class HomeController : Controller
    {
        
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: Home
        public ActionResult Index()
        {
            // Lan luot tao cac viewbag de lay list sanpham tu co so du lieu
            //List dien thoia moi nhat

            var lstDTM = db.SanPhams.Where(n => n.MaLoaiSP == 1 && n.Moi == 1 && n.DaXoa == false);
            ViewBag.ListDTM = lstDTM;
            //  Gan vao viewbag
            var lstLTM = db.SanPhams.Where(n => n.MaLoaiSP == 2 && n.Moi == 1 && n.DaXoa == false);
            ViewBag.ListLTM = lstLTM;


            var lstMTB = db.SanPhams.Where(n => n.MaLoaiSP == 3 && n.Moi == 1 && n.DaXoa == false);

            ViewBag.ListMTB = lstMTB;
            
            return View();
        }

        public ActionResult MenuParial()
        {
            // Truy vấn lấy về 1 list sản phẩm
            var LstSP = db.SanPhams;
          
            return PartialView(LstSP);
        }
        public ActionResult ThanhtraiPatial()
        {
            // Truy vấn lấy về 1 list sản phẩm
            var LstSP = db.SanPhams;
            
            var lstBanChayNhat = db.SanPhams.Where(n => n.SoLanMua > 0).Max(p => p.SoLanMua);
            ViewBag.ListBCN = lstBanChayNhat;
            return PartialView(LstSP);
        }
       
         
          
        [HttpGet]
        public ActionResult Dangky()

        {
            ViewBag.CauHoi = new SelectList(LoadCauHoi());
            return View();
        }


        [HttpPost]
        public ActionResult Dangky(ThanhVien tv, FormCollection f)
        {
            ViewBag.CauHoi = new SelectList(LoadCauHoi());
            //Kiểm tra captcha hợp lệ
            if (this.IsCaptchaValid("Captcha không hợp lệ"))
            {
                if (ModelState.IsValid)
                {
                    ViewBag.ThongBao = "Thêm thành công";
                    db.ThanhViens.Add(tv);
                    db.SaveChanges();
                }
                else
                {
                    ViewBag.ThongBao = "Thêm thất bại";
                }
                return View();
            }
            //Thêm khách hàng vào csdl
            ViewBag.ThongBao = "Sai mã captcha";


            return View();
        }

        [HttpGet]
        public ActionResult Dangky1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky1(ThanhVien tv)
        {
            return View();
        }
        // Load câu hỏi bí mật
        public List<string> LoadCauHoi()
        {
           
            List<string> lstCauHoi = new List<string>();
            lstCauHoi.Add("Con vật mà bạn yêu thích?");
            lstCauHoi.Add("Ca sĩ mà bạn yêu thích?");
            lstCauHoi.Add("Hiện tại bạn đang làm công việc gì?");
            return lstCauHoi;
        }
        //Xây dựng action đăng nhập
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            
            //Kiểm tra đăng nhập mật khẩu
            //string sTaiKhoan = f["txtTenDangNhap"].ToString();
            //string sMatKhau = f["txtMatKhau"].ToString();
            //ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            //if (tv != null)
            //{
            //    Session["TaiKhoan"] = tv;
            //    return Content("<script>window.location.reload();</script>");
            //}
            //return Content("Tài khoản hoặc mật khẩu không đúng");
            string taikhoan = f["txtTenDangNhap"].ToString();
            string matkhau = f["txtMatKhau"].ToString();
            //Truy vấn kiểm tra đăng nhập lấy thông tin thành viên
            ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.TaiKhoan == taikhoan && n.MatKhau == matkhau);
            if (tv != null)
            {
                // lấy ra list quyền của thành viên tương ứng với loại thành viên
                var lstQuyen = db.LoaiThanhVien_Quyen.Where(n => n.MaLoaiTV == tv.MaLoaiTV);
                //Duyệt list quyền
                string Quyen = "";
                if(lstQuyen.Count() != 0)
                { 
                foreach(var item in lstQuyen)
                {
                    Quyen += item.Quyen.MaQuyen + ",";
                }
                Quyen = Quyen.Substring(0, Quyen.Length - 1);//Cắt đi dấu phẩy cuối
                PhanQuyen(tv.TaiKhoan.ToString(), Quyen);
                    Session["TaiKhoan"] = tv;
                    return Content("<script>window.location.reload();</script>");
                }
            }
            return Content("Tài khoản hoặc mật khẩu không đúng");
        }
   public void PhanQuyen(string TaiKhoan, string Quyen)
        {
            FormsAuthentication.Initialize();
            var ticket = new FormsAuthenticationTicket(1, TaiKhoan,
                DateTime.Now,//Thời gian khởi tạo
                DateTime.Now.AddHours(3),//Thời gian kết thúc
                false, //Ghi nhớ
                Quyen,
                FormsAuthentication.FormsCookiePath);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
            if (ticket.IsPersistent)
            {
                cookie.Expires = ticket.Expiration;
            }
            Response.Cookies.Add(cookie);

        }
        //Tạo trang ngăn chặn quyền truy cập
        public ActionResult LoiPhanQuyen()
        {

            return View();
        }
        public ActionResult XemThongTin()
        {
            return View();
        }
        public ActionResult DangXuat()
        {
            Session["TaiKhoan"] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }

    }
}

WedSiteBanHang/WedSiteBanHang/Controllers/LienHeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WedSiteBanHang.Controllers
{
    public class LienHeController : Controller
    {
        // GET: LienHe
        public ActionResult Index()
        {
            return View();
        }
    }
}

WedSiteBanHang/WedSiteBanHang/Views/Home/Dangky.cshtml
@model WedSiteBanHang.Models.ThanhVien
@using CaptchaMvc.HtmlHelpers;
@using CaptchaMvc;


@{
    ViewBag.Title = "Dangky";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}
<div class="col-md-9">

    <div class="Dangky" style="width: 1000px;margin-left: 100px;">
        <h1 style="padding-top: 0px;height: 20px;" >Đăng ký thành viên</h1>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="col-md-4 register-top-grid">
                <h3>Thông tin cá nhân</h3>
                <div>
                    <span>@Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-4" })</span>
                    @Html.TextBoxFor(Model => Model.TaiKhoan)
                    @Html.ValidationMessageFor(model => model.TaiKhoan)


                </div>

                <div>
                    @Html.TextBoxFor(Model => Model.HoTen)
                    @Html.ValidationMessageFor(model => model.HoTen)

                </div>
                <div>
                    <span>Địa chỉ</span>
                    @Html.TextBox("DiaChi")
                </div>
                <div>
                    <span>Email</span>
                    @Html.TextBox("Email")
                </div>
                <div>
                    <span>Số điện thoại</span>
                    @Html.TextBox("SoDienThoai")
                </div>

            </div>
            <div class="col-md-4 register-bottom-grid  register-top-grid">
                <h3>Thông tin đăng nhập</h3>
                <div>
                    <span>Mật khẩu</span>
                    @Html.Password("MatKhau")
                </div>
                <div>
                    <span>Nhập lại mật khẩu</span>
                    @Html.Password("NhapLaiMatKhau")
                </div>

                <div>
                    <span>Câu hỏi bí mật</span>
                    @Html.DropDownList("CauHoi")
                </div>
                <div>
                    <span>Câu trả lời</span>
                    @Html.TextBox("CauTraLoi")
                </div>
                <div>
                    @Html.Captcha(5);
                </div>
                <input value="Xác nhận" type="submit">

            </div>
            <div class="clearfix"> </div>
        }
        <h1 style="color:red;padding-top: 0px;">@ViewBag.ThongBao</h1>

    </div>

</div>

WedSiteBanHang/WedSiteBanHang/Views/Home/Dangky1.cshtml
@model WedSiteBanHang.Models.ThanhVien

@{
    ViewBag.Title = "Dangky1";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}

<h2>Dangky1</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="col-md-9 register-top-grid">
        <div class="form-horizontal">

            <h4>ThanhVien</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MaThanhVien, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.MaThanhVien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaThanhVien, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CauHoi, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.CauHoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CauHoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CauTraLoi, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.CauTraLoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CauTraLoi, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

WedSiteBanHang/WedSiteBanHang/Views/Home/Index.cshtml
@using  WedSiteBanHang.Models
@model IEnumerable<SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
@{ 
    IEnumerable<SanPham> lstDTM = (IEnumerable<SanPham>)ViewBag.ListDTM;
    IEnumerable<SanPham> lstLTM = (IEnumerable<SanPham>)ViewBag.ListLTM;
    IEnumerable<SanPham> lstMTB = (IEnumerable<SanPham>)ViewBag.ListMTB;

}
@Html.RouteLink("CLick vào đây để mở trang khách hàng", "KhachHang")


        <div class="content-top">
        <h1> Điện thoại mới nhất</h1>

        <div class="grid-in">
            <div class="container">
                @Html.Partial("~/Views/SanPham/SanPhamStyle1Partial.cshtml", lstDTM)
            </div>
            </div>
            <h1> Máy tính xách tay mới nhất</h1>
            <div class="grid-in">
                <div class="container">
                    @Html.Partial("~/Views/SanPham/SanPhamStyle2Partial.cshtml", lstLTM)
                </div>
            </div>
            <h1> Máy tính bảng mới nhất </h1>

            <div class="grid-in">
                @*Maytinh bang*@
                <div class="container">
                    @Html.Partial("~/Views/SanPham/SanPhamStyle1Partial.cshtml", lstMTB)
                </div>
            </div>
    </div>

WedSiteBanHang/WedSiteBanHang/Views/Home/LoiPhanQuyen.cshtml
@{
    ViewBag.Title = "LoiPhanQuyen";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>
    Bạn không đủ quyền truy cập vào trang này vui lòng trở về trang chủ
    @Html.ActionLink("Trở về", "Index", "Home", null, null)
</h2>

WedSiteBanHang/WedSiteBanHang/Views/Home/MenuParial.cshtml
@using WedSiteBanHang.Models
@model IEnumerable<SanPham>

<div class="h_menu4">
    <ul class="memenu skyblue">
        <li class="showhide" style="display: none;"><span class="title">MENU</span><span class="icon1"></span><span class="icon2"></span></li>
        <li class="active grid" style="display: inline;"><a class="color8" href="@Url.Action("Index","Home")"> Trang chủ</a></li>

@foreach (var groupItem in Model.GroupBy(n => n.LoaiSanPham))
{
    if (groupItem.Key != null)
    {
        <li style="display: inline;">
            <a class="color1" href="#">@groupItem.Key.TenLoai</a>
            <div class="mepanel" style="display: none; opacity: 1;">
                <div class="row">
                    <div class="col1">
                        <div class="h_nav">
                            <ul>
                                @foreach (var item in groupItem.GroupBy(n => n.NhaSanXuat))
                                {
                                    if (item.Key != null)
                                    {
                                        <li><a href="@Url.Action("SanPham", "SanPham", new {@MaLoaiSP=groupItem.Key.MaLoaiSP,@MaNSX=item.Key.MaNSX })">@item.Key.TenNSX</a></li>

                                    }
                                }
                                
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    }

}

                 
        <li class="grid" style="display: none;">
            <a class="color2" href="#">	Thương hiệu</a>
            <div class="mepanel" style="display: none;">
                <div class="row">
                  @foreach (var groupItem in Model.GroupBy(n => n.LoaiSanPham))
                  {
                      if (groupItem.Key != null)
                      {
                        <div class="col1">
                            <div class="h_nav">
                                <h4>@groupItem.Key.TenLoai</h4>
                                <ul>
                                    @foreach (var item in groupItem.GroupBy(n => n.NhaSanXuat))
                                    {
                                        if (item.Key != null)
                                        {
                                            <li><a href="@Url.Action("SanPham", "SanPham", new {@MaLoaiSP=groupItem.Key.MaLoaiSP,@MaNSX=item.Key.MaNSX })">@item.Key.TenNSX</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                      }

                  }
                   
                </div>
            </div>
        </li>
        <li style="display: none;"><a class="color4" href="@Url.Action("XemGioiThieu","SanPham")">Giới thiệu</a></li>
        <li style="display: none;"><a class="color6" href="https://www.facebook.com/profile.php?id=100043800910011">Liên hệ</a>
            <div class="mepanel" style="display:none; position:center;">
                <div class="row">
                            <div class="col1">
                                <div class="h_nav">
                                    <ul>
                                   <li><a href="https://www.facebook.com/profile.php?id=100043800910011">Liên hệ qua facebook</a></li>
                                        <li><a href="@Url.Action("Index","LienHe")">Liên hệ gmail</a></li>

                                    </ul>
                                </div>
                            </div>
                </div>
            </div>
        
        </li>
    </ul>
</div>

WedSiteBanHang/WedSiteBanHang/Views/Home/ThanhtraiPatial.cshtml
@using WedSiteBanHang.Models
@model IEnumerable<SanPham>
<div class="col-md-3 product-price">

    <div class="rsidebar span_1_of_left">
        <div class="of-left">
            <h3 class="cate">Các sản phẩm</h3>
        </div>
        <ul class="menu">

            @foreach (var groupItem in Model.GroupBy(n => n.LoaiSanPham))
            {
                if (groupItem.Key != null)
                {
                    <li class="item1">
                        <a href="#">@groupItem.Key.TenLoai </a>
                        <ul class="cute">
                            @foreach (var item in groupItem.GroupBy(n => n.NhaSanXuat))
                            {
                                if (item.Key != null)
                                {
                                    <li class="subitem1"><a href="@Url.Action("SanPham", "SanPham", new {@MaLoaiSP=groupItem.Key.MaLoaiSP,@MaNSX=item.Key.MaNSX })">@item.Key.TenNSX </a></li>

                                }

                            }

                        </ul>
                    </li>
                }
            }


         
        </ul>
    </div>
    <!--initiate accordion-->
    <script type="text/javascript">
			$(function() {
			    var menu_ul = $('.menu > li > ul'),
			           menu_a  = $('.menu > li > a');
			    menu_ul.hide();
			    menu_a.click(function(e) {
			        e.preventDefault();
			        if(!$(this).hasClass('active')) {
			            menu_a.removeClass('active');
			            menu_ul.filter(':visible').slideUp('normal');
			            $(this).addClass('active').next().stop(true,true).slideDown('normal');
			        } else {
			            $(this).removeClass('active');
			            $(this).next().stop(true,true).slideUp('normal');
			        }
			    });

			});
    </script>
    <!---->
    <div class="product-middle">

        <div class="fit-top">
            <h6 class="shop-top">Lorem Ipsum</h6>
            <a href="single.html" class="shop-now">SHOP NOW</a>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="sellers">
        <div class="of-left-in">
            <h3 class="tag">Tags</h3>
        </div>
        <div class="tags">
            <ul>
                <li><a href="#">design</a></li>
                <li><a href="#">fashion</a></li>
                <li><a href="#">lorem</a></li>
                <li><a href="#">dress</a></li>
                <li><a href="#">fashion</a></li>
                <li><a href="#">dress</a></li>
                <li><a href="#">design</a></li>
                <li><a href="#">dress</a></li>
                <li><a href="#">design</a></li>
                <li><a href="#">fashion</a></li>
                <li><a href="#">lorem</a></li>
                <li><a href="#">dress</a></li>

                <div class="clearfix"> </div>
            </ul>

        </div>

    </div>
    <!---->
    <div class="product-bottom">
        <div class="of-left-in">
            <h3 class="best">Bán chạy nhất</h3>
        </div>
@foreach (var item in Model.Where(n => n.SoLanMua == @ViewBag.ListBCN))
{
        <div class="product-go">
            <div class="fashion-grid">
                <a href="@Url.Action("XemChiTiet", "SanPham", new { id = item.MaSP})"><img class="img-responsive " src="@Url.Content("~/Content/images/"+item.HinhAnh)" alt=""></a>

            </div>
            <div class="fashion-grid1">
                <h6 class="best2">
                    <a href="@Url.Action("XemChiTiet", "SanPham", new { id = item.MaSP})">
                       @item.CauHinh
                    </a>
                </h6>

                <span class="price-in1">@item.DonGia</span>
            </div>

            <div class="clearfix"> </div>
        </div>
}
       

    </div>
    <div class="per1">
        <a href="single.html">
            <img class="img-responsive" src="~/Content/images/iphone.png" alt="">
            <div class="six1">
                <h4>Giảm giá</h4>
                <p>Up to</p>
                <span>60%</span>
            </div>
        </a>
    </div>
</div>

WedSiteBanHang/WedSiteBanHang/Views/Home/XemThongTin.cshtml
@{
    ViewBag.Title = "XemThongTin";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}

<h2>XemThongTin</h2>